apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
  - name: mypod
    image: centos
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    volumeMounts:
    - mountPath: /largevol
      name: largevol
  volumes:
    - name: largevol
      persistentVolumeClaim:
        claimName: large-vol
